# -*- coding: utf-8 -*-
"""exp3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ogp7PHx2vSa5B8acEWxhuLDwkQNah-_N
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
data = {
    'CGPA': [5.5, 6.0, 6.2, 6.5, 6.8, 7.0, 7.2, 7.5, 7.8, 8.0,
             8.2, 8.5, 8.7, 9.0, 9.2],

    'Package': [2.5, 2.8, 3.0, 3.2, 3.5, 3.8, 4.0, 4.3, 4.6, 4.8,
                5.0, 5.5, 5.8, 6.2, 6.5]
}

df = pd.DataFrame(data)

print("First 5 rows:")
print(df.head())

print("\nDataset shape:")
print(df.shape)

print("\nDataset information:")
df.info()

print("\nStatistical summary:")
print(df.describe())
print(df.isnull().sum())

X = df[['CGPA']]       # Independent variable
y = df['Package']

print("Independent Variable (X): CGPA")
print("Dependent Variable (y): Package")

plt.figure(figsize=(8, 5))


plt.scatter(X, y)


plt.xlabel("CGPA")
plt.ylabel("Placement Package (LPA)")
plt.title("CGPA vs Placement Package")


plt.show()

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)


print("Training data:")
print(X_train)


print("\nTesting data:")
print(X_test)

model = LinearRegression()
model.fit(X_train, y_train)


print("Model training completed.")

print("Slope (β1):", model.coef_[0])
print("Intercept (β0):", model.intercept_)

y_pred = model.predict(X_test)


print("Actual values:")
print(y_test.values)


print("\nPredicted values:")
print(y_pred)
# Compare actual and predicted values
comparison = pd.DataFrame({
    'CGPA': X_test['CGPA'].values,
    'Actual Package': y_test.values,
    'Predicted Package': y_pred
})

r2 = r2_score(y_test, y_pred)


print("R² Score:", r2)
print("R² Percentage:", r2 * 100, "%")

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)


print("Mean Absolute Error:", mae)
print("Mean Squared Error:", mse)

plt.figure(figsize=(8, 5))


plt.scatter(X, y, label="Actual Data")


plt.plot(X, model.predict(X), label="Regression Line")


plt.xlabel("CGPA")
plt.ylabel("Placement Package (LPA)")
plt.title("Simple Linear Regression: CGPA vs Placement Package")


plt.legend()
plt.show()

new_cgpa = [[8.5]]


predicted_package = model.predict(new_cgpa)


print("CGPA:", new_cgpa[0][0])
print("Predicted Placement Package:", predicted_package[0], "LPA")

new_students = [[7.0], [8.0], [8.5], [9.0], [9.5]]


predicted_packages = model.predict(new_students)


for cgpa, package in zip(new_students, predicted_packages):
    print(f"CGPA: {cgpa[0]} -> Predicted Package: {package:.2f} LPA")

